mod deep_diagnose;
mod knowledge;
mod mcp;
mod ocr;
mod remote;
mod repair;
mod speech;
mod versions;
mod wiring;
mod workspace;
mod workspace_files;

pub use deep_diagnose::*;
pub use knowledge::*;
pub use mcp::*;
pub use ocr::*;
pub use remote::*;
pub use repair::*;
pub use speech::*;
pub use versions::*;
pub use wiring::*;
pub use workspace::*;
pub use workspace_files::*;
